"""Bake the HGSS message charmap into charmap_data.py so the patcher is self-contained
(no dependency on the decomp refs at runtime -> works inside the delivered .exe).

Run once to (re)bake:
    ironmon-scout/.venv/Scripts/python.exe ironmon-scout/tools/gen_charmap.py
"""
import os, re

REFS = os.path.join(os.path.dirname(__file__), "..", "refs", "pokeheartgold")
SRC = os.path.join(REFS, "charmap.txt")
OUT = os.path.join(os.path.dirname(__file__), "charmap_data.py")

entries = []  # (code, raw string) in file order
for line in open(SRC, encoding="utf-8"):
    line = line.rstrip("\n")
    if not line or line.lstrip().startswith("//"):
        continue
    m = re.match(r"\s*([0-9A-Fa-f]{4})=(.*)$", line)
    if m:
        entries.append((int(m.group(1), 16), m.group(2)))

with open(OUT, "w", encoding="utf-8") as f:
    f.write('"""GENERATED by gen_charmap.py from the decomp charmap.txt. Do not edit by hand.\n')
    f.write('code -> character/escape string (file order preserved for first-match encoding)."""\n')
    f.write("CODE2S = {\n")
    for code, s in entries:
        f.write(f"    0x{code:04X}: {s!r},\n")
    f.write("}\n")

print(f"baked {len(entries)} charmap entries -> {OUT}")
