"""Generate species_ow_sprite.py: national-dex species -> overworld (follower) sprite ID.

    spriteId(species) = SPRITE_FOLLOWER_MON_BULBASAUR(428) + sModelIndexLUT[species]

sModelIndexLUT (follow_mon.c) is indexed by dex# ([0]=NONE) and holds FOLLOWER_MON_* offset
constants (follow_mon_idx.h). Base (male/genderless, form 0) sprite per species — which is what
we want for a scout ball, since the wild mon's gender/form is rolled at battle time.

Run once to (re)bake the map:
    ironmon-scout/.venv/Scripts/python.exe ironmon-scout/tools/gen_species_ow.py
"""
import re, os

REF = os.path.join(os.path.dirname(__file__), "..", "refs", "pokeheartgold")
IDX_H = os.path.join(REF, "include", "constants", "follow_mon_idx.h")
FOLLOW_C = os.path.join(REF, "src", "follow_mon.c")
BASE = 428  # SPRITE_FOLLOWER_MON_BULBASAUR
OUT = os.path.join(os.path.dirname(__file__), "species_ow_sprite.py")

# 1) FOLLOWER_MON_<NAME> -> numeric offset
name2off = {}
for line in open(IDX_H, encoding="utf-8"):
    m = re.match(r"\s*#define\s+(FOLLOWER_MON_\w+)\s+(\d+)", line)
    if m:
        name2off[m.group(1)] = int(m.group(2))

# 2) sModelIndexLUT[] -> ordered FOLLOWER_MON_* names (index = dex#, [0]=NONE)
src = open(FOLLOW_C, encoding="utf-8").read()
body = src.split("sModelIndexLUT[] = {", 1)[1].split("};", 1)[0]
names = re.findall(r"(FOLLOWER_MON_\w+)", body)

# 3) dex# -> sprite id  (skip index 0 = NONE)
sprite = {}
for dex, nm in enumerate(names):
    if dex == 0:
        continue
    sprite[dex] = BASE + name2off[nm]

assert sprite[1] == 428, sprite[1]           # Bulbasaur
assert max(sprite.values()) <= 993, max(sprite.values())
print(f"{len(sprite)} species, sprite IDs {min(sprite.values())}..{max(sprite.values())}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write('"""GENERATED by gen_species_ow.py — national-dex species -> follower OW sprite ID.\n')
    f.write('spriteId = 428 + sModelIndexLUT[species]. Do not edit by hand."""\n')
    f.write("SPECIES_OW_SPRITE = {\n")
    for dex in sorted(sprite):
        f.write(f"    {dex}: {sprite[dex]},\n")
    f.write("}\n")
print("wrote", OUT)

# sanity: show the current Route 29 (random2) test species
for dex, label in [(76, "Golem"), (289, "Slaking"), (368, "Gorebyss"),
                   (16, "Pidgey"), (3, "Venusaur"), (4, "Charmander")]:
    print(f"  {label:10} dex {dex:3} -> sprite {sprite.get(dex)}")
